language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

gemfile:
  - Gemfile.ci

notifications:
  email: projmgr@arxopia.com

before_install:
	- apt-get install git-core subversion cvs
  - gem update --system
  - gem --version
